version: '3.9'

services:
    server-app:
        build:
            context: .
            dockerfile: ../laravel.Dockerfile
        restart: unless-stopped
        env_file: .env.common
        depends_on:
            server-postgres: { condition: service_healthy }
            server-migrator: { condition: service_completed_successfully }
        volumes:
            - ./:/workdir
        networks:
            - server

    server-migrator:
        build:
            context: .
            dockerfile: ../laravel.Dockerfile
        command: php artisan migrate --force --seed
        restart: on-failure
        env_file: .env.common
        depends_on:
            server-postgres: { condition: service_healthy }
        networks:
            - server

    server-nginx:
        image: nginx:latest
        ports:
            - '8000:80'
        volumes:
            - ./.nginx/nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/workdir
        restart: unless-stopped
        depends_on:
            server-app: { condition: service_started }
        networks:
            - server

    server-postgres:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB?}
            - POSTGRES_USER=${POSTGRES_USER?}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?}
        ports:
            - '5433:5432'
        restart: always
        healthcheck:
            test: pg_isready -d ${POSTGRES_DB?} -U ${POSTGRES_USER?}
        volumes:
            - server-postgres:/var/lib/postgresql/data
        networks:
            - server

volumes:
    server-postgres: { }

networks:
    server:
        driver: bridge
